# Generated by Django 5.1.3 on 2024-12-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immobilier', '0002_alter_utilisateur_numero_cni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='prix',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
